name: Build LaTeX document

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup LaTeX environment
      uses: dante-ev/latex-action@v2

    - name: Compile LaTeX document
      run: pdflatex -interaction=nonstopmode -halt-on-error resume.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: resume.pdf